# -*- coding: utf-8 -*-
"""CancerPrediction_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14umztHyYC3IlF1H8lM2RmmlCVbhDDsEb
"""

#importing libraries
import pandas as pd

#importing dataset
dataset=pd.read_csv('cancer.csv')

# setting up x 
x = dataset.drop(columns=['diagnosis(1=m, 0=b)'])

#setting up y
y = dataset["diagnosis(1=m, 0=b)"]

#determine the test and training splits
#i am using 80/20 ratio split here

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2)

#import the model 
import tensorflow as tf
model = tf.keras.models.Sequential()

#adding layers to the model
model.add(tf.keras.layers.Dense(256, input_shape= (x_train.shape[1],), activation='sigmoid'))
model.add(tf.keras.layers.Dense(256, activation='sigmoid'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

#compiling the model
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

#fitting the model used 100 epochs only 
model.fit(x_train, y_train, epochs=1000)